### PR TITLE
Add gridrec example to VisTrails

### PR DESCRIPTION
**Pull request by celiafish**
Gridrec workflow from Tomopy with visualization with vtk.

### CODE REVIEW

**Comment by tacaswell** [comment]
@giltis Can you make sure you can get this to run on your computer?

**Comment by giltis** [comment]
yep, I'll get to it this afternoon. Totally missed this posting.

**Comment by celiafish** [comment]
Many thanks!

**Comment by ericdill** [comment]
@giltis any updates on this?

**Comment by ericdill** [comment]
@giltis bump

**Comment by giltis** [comment]
Wei, we need the associated data in order to get the demo to run through. Can you include a download_data.py file making the example data accessible? Otherwise, if you can bring it by on a thumb drive, I can make the downloader and post the data so that it is hosted and available.

**Comment by celiafish** [comment]
Gabe, here is the data link: https://github.com/tomopy/tomopy/blob/legacy/demo/data.h5 . Although, I don't think it is necessary to have a download_data.py file included, since the purpose of this PR is to show Tomopy and VisTrails' visualization capability. But if you want to add that file, I suggest you adding it up through VTTools. So people can benefit from it most, when they want to acquire data online. Thanks.

**Comment by giltis** [comment]
Wei, looks like we're now clear and ready to go on both fronts.

**Comment by celiafish** [comment]
Gabe, can you upload the updated vt file, so I can test?

**Pull request merged**
