### PR TITLE
ENH: added new example notebook for selecting different ROI shapes

### PR DESCRIPTION
**Pull request by sameera2004**

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you use a color map which is not jet? I like `'dark2'`, `'set2'` or `'set3'` for this sort of thing

http://matplotlib.org/users/plotting/colormaps/lightness_03.png
so

**Comment by sameera2004** [comment]
@tacaswell sure, Thanks I will use a different color map

**Comment by ericdill** [comment]
Can you change the first plot to use the `interpolation=None` kwarg?

**Comment by tacaswell** [comment]
I would also suggest using https://github.com/tacaswell/xray-vision/blob/master/xray_vision/mpl_plotting.py#L90 which is to make plotting labeled masks easier.

**Comment by ericdill** [comment]
At the end of this notebook can you add 

```python
import skxray
print(skxray.__version__)
```

**Comment by sameera2004** [comment]
added version  ..., used X-ray_vision.mpl_plotting.roi tools
ready for review

**Comment by sameera2004** [comment]
Here is the nbviewer link
http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/roi/demos/Generate_ROI_labeled_arrays.ipynb

**Comment by ericdill** [comment]
Thanks for the updates

**Comment by ericdill** [comment]
Typo in cell 8:
Currently says `axes.set_title("Differnt sapcing between rings")`
Should say `axes.set_title("Different spacing between rings")`

**Comment by sameera2004** [comment]
Thanks I will fix these

**Comment by ericdill** [comment]
It would appear that you are not using scikit-xray master, given that the version string at the end of this notebook is `0.0.4+110.gfdd0b8a.dirty`. Is there a reason you are not using scikit-xray master for these?  The version string should be `0.0.4-105-ge27b978` as of tom's merge to master of scikit-xray/scikit-xray#333

**Comment by sameera2004** [comment]
@ericdill fixed the typos and the skxray.version ready for review, here's the nbviewer link
http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/roi/demos/Generate_ROI_labeled_arrays.ipynb

**Comment by ericdill** [comment]
Looks great! Thanks @sameera2004 !

**Comment by sameera2004** [comment]
Thanks Eric

**Pull request merged**
