### PR TITLE
ENH: added example notebook for xsvs ( skxray.core.spackle module fun…

### PR DESCRIPTION
**Pull request by sameera2004**
…ctions)

### CODE REVIEW

**Comment by sameera2004** [comment]
@ericdill added an example notebook for xsvs analysis(skxray.core.speckle)

**Comment by sameera2004** [comment]
@ericdill I updated this after merging your PR

**Comment by sameera2004** [comment]
ready for review, only one top-level heading

**Comment by danielballan** [comment]
Would you post an nbviewer link, please?

**Comment by sameera2004** [comment]
@danielballan here is the nbviewer link for xsvs analysis http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/xsvs/demos/speckle/X-ray_Speckle_Visibility_Spectroscopy.ipynb

**Comment by ericdill** [comment]
At the end of this notebook can you add 

```python
import skxray
print(skxray.__version__)
```

**Comment by ericdill** [comment]
Similar to your other PR, can you use https://github.com/tacaswell/xray-vision/blob/master/xray_vision/mpl_plotting.py#L90 for the ROI plotting?

**Comment by sameera2004** [comment]
@ericdill sure I will add _version_ and use the X-ray_vision/mpl_plotting

**Comment by sameera2004** [comment]
Fixed this PR (added skxray version now using X-ray_vision/mpl_plotting)
Reday for review

**Comment by tacaswell** [comment]
Looks great!

Only comment is to use a linear color map in cell 5

**Comment by sameera2004** [comment]
@tacaswell sure thanks, which colormap you suggest? I am trying different ones didn't find a good one!

**Comment by tacaswell** [comment]
'viridis', failing that 'hot' or 'gray'

**Comment by sameera2004** [comment]
@tacaswell ready for review changed the colormap to `viridias`, ready for review

new nbviwer link
http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/xsvs/demos/speckle/X-ray_Speckle_Visibility_Spectroscopy.ipynb

**Pull request merged**
