### PR TITLE
ENH: added ipython notebook and data for XPCS data fitted with ISF us…

### PR DESCRIPTION
**Pull request by sameera2004**
…ing lmfit

### CODE REVIEW

**Comment by sameera2004** [comment]
@ericdill and @licode , I added a python notebook for correlation data fitted with ISF using lmfit

**Comment by ericdill** [comment]
Please squash the first two commits so that git thinks you never added the .zip file. As it stands, the .zip file is part of git history and so this repo will increase by whatever that size is

**Comment by sameera2004** [comment]
@ericdill I squashed the commits, ready to go!

**Comment by sameera2004** [comment]
took out unwanted top-level headings, leaving only one in this notebook

**Comment by sameera2004** [comment]
here is the nbviwer link for XPCS fitting using ISF

http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/corr_fit/demos/1_time_correlation/XPCS_data_fiiting_using_ISF.ipynb

**Comment by ericdill** [comment]
At the end of this notebook can you add 

```python
import skxray
print(skxray.__version__)
```

**Comment by ericdill** [comment]
Can you change the title to 

```
# XPCS fitting with lmfit
```

**Comment by ericdill** [comment]
And make the rest a sub-heading

**Comment by sameera2004** [comment]
@ericdill 
Changed the name of the ipnb, added the version..,
used mol_plotting.roi tools for plot the labeled_array this is ready for review

**Comment by sameera2004** [comment]
Here is the nbviewer link
http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/corr_fit/demos/1_time_correlation/XPCS_fitting_with_lmfit.ipynb

**Comment by ericdill** [comment]
Is this using your `new_xsvs_fit` branch on scikit-xray?

**Comment by ericdill** [comment]
I'm trying to figure out what is different about your version of scikit-xray, given that your version string is `0.0.4+110.gfdd0b8a.dirty`

**Comment by sameera2004** [comment]
@ericdill no this is XPCS(not XSVS)

**Comment by ericdill** [comment]
I'm confused by your renaming of `utils` to `core` in your import: `import skxray.core.utils as core`. Would it be possible to keep the name utils: `import skxray.core.utils as utils`?

**Comment by ericdill** [comment]
Can you also create a zoomed-in figure for cell 7 so that it is easier to see what is going on with the ROI rings?  The cell I'm referring to is the one under the heading `Create a labeled array using roi.rings`

**Comment by sameera2004** [comment]
@ericdill first I put a zoomed-in figure, but when I am plotting a zoomed figure it rotate by 90,

screen shot 2015-09-17 at 10 06 40 am

**Comment by sameera2004** [comment]
@ericdill I fixed the version thing, changed the import skxray.core.utils as utils, and zoomed the figure
ready for review

**Comment by sameera2004** [comment]
new nbviwer link http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/corr_fit/demos/1_time_correlation/XPCS_fitting_with_lmfit.ipynb

**Comment by ericdill** [comment]
Can you add this example to the readme

**Comment by ericdill** [comment]
Can you label the one-time correlation plots with their Q-value?

**Comment by ericdill** [comment]
And by label I mean either title or legend, I have no strong preferences between either option

**Comment by sameera2004** [comment]
@ericdill Added the Q-value title to the plots
https://github.com/sameera2004/scikit-xray-examples/blob/corr_fit/demos/1_time_correlation/XPCS_fitting_with_lmfit.ipynb

Eric right now `readme file is broken` (links are broken), once you merge this I will take care of that, I will add all the examples we have so far to that read me file

**Comment by ericdill** [comment]
Ok, sounds good

**Comment by ericdill** [comment]
PR looks great. Thanks @sameera2004 !

**Comment by sameera2004** [comment]
Thanks Eric

**Pull request merged**
